### ISSUE TITLE
My hunter does not Connect, Error code 401

### ISSUE THREAD

**Issue by richardhop** [mjilesen/com.hydrawise#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mjilesen** [comment]
Have you filled in an api key? 401 means unauthorized....

Op za 10 jun. 2023 13:18 schreef Richard Hop ***@***.***>:

**Comment by richardhop** [comment]
Hello, I die not see anny Field for an api KeyMet vriendelijke groet,Richard HopOp 10 jun. 2023 om 13:24 heeft mjilesen ***@***.***> het volgende geschreven:﻿
Have you filled in an api key? 401 means unauthorized....



Op za 10 jun. 2023 13:18 schreef Richard Hop ***@***.***>:

**Comment by mjilesen** [comment]
Hi,

In the Homey app:
Go to "more" -> Apps ->Hunter Hydrawise->select setting in the right corner ->App settings

Follow the instructions there to get and set the api key.

Regards, Monique
________________________________
Van: Richard Hop ***@***.***>
Verzonden: zaterdag 10 juni 2023 14:18
Aan: mjilesen/com.hydrawise ***@***.***>
CC: mjilesen ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [mjilesen/com.hydrawise] My hunter does not Connect, Error code 401 (Issue #12)


Hello, I die not see anny Field for an api KeyMet vriendelijke groet,Richard HopOp 10 jun. 2023 om 13:24 heeft mjilesen ***@***.***> het volgende geschreven:﻿
Have you filled in an api key? 401 means unauthorized....



Op za 10 jun. 2023 13:18 schreef Richard Hop ***@***.***>:

**Comment by richardhop** [comment]
Thynx

Its working …


Kind regards,


R.C. Hop



R.C. Hop Holding B.V.
Dorpsstraat 58 | 3651ES Bunschoten
t. +31 (0) 33 298 3827 | m. +31 (0) 6 53 306 449
e. ***@***.***
