### ISSUE TITLE
Hydrawise PRO-HC

### ISSUE THREAD

**Issue by oksdol** [mjilesen/com.hydrawise#7]
Very happy to see support for Hydrawise! However, I have the Hydrawise PRO-HC and when I try to connect I get the attached error message. Any chance you could fix this? 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/53821460/178965394-76db54c1-d6c6-4f65-846e-f81f0687d4d1.png">

**Comment by mjilesen** [comment]
Did you fill in the API Key for you account? 401 means that you are not authorized.

Goto Apps/Hunter Hydrawise and then on the bottom there is the option "configure app". There you have to fill in an API key. I have added links on that page how to get an API key from Hunter.

**Comment by oksdol** [comment]
That worked, thanks! Sorry for now checking the documentation first!
