### ISSUE TITLE
Not reporting irrigation status

### ISSUE THREAD

**Issue by oksdol** [mjilesen/com.hydrawise#8]
I have now successfully added 6 Hydrawise irrigation zones in Homey. I want to automatically start the pump in the well which is controlled with a Shelly Wifi Socket when one of the Hydrawise zones is started with a program in Hydrawise. However, when a zone is started by Hydrawise, it is not successfully reporting the status "On" to Homey. Also, I suspect that you should add an "If" action based on "Zone started/stopped running". Or maybe "On" status should be defined as "Zone is running"? Please check the attachments. Any chance to resolve this? I made a donation yesterday to support this app!
<img width="918" alt="Screen Shot 2022-07-15 at 14 50 55" src="https://user-images.githubusercontent.com/53821460/179228601-3a4a851f-6ca5-4787-91b1-011330d5a165.png">
![Screenshot 2022-07-15 at 14 52 45](https://user-images.githubusercontent.com/53821460/179228611-9776a277-ced2-4c61-a18c-c7606efaeee8.jpeg)

**Comment by mjilesen** [comment]
The way you configured it should work (and works on my system). In the setting page, do you have "status updates" turned on? If so, what is the update frequency?

**Comment by oksdol** [comment]
OK, thanks! Status updates was not turned on. According to Hydrawise's API documentation, it seems like they allow up to 30 call per 5 minute, meaning no average a call per 10 seconds. Hence, I assume that a call per 60 seconds should be fine?

**Comment by mjilesen** [comment]
If you start your zones from the Hydrawise app (or let the app start them), you will need to turn them on. I would set it as large as possible (=> which frequency works best for you). 
If you only use the Homey app, please turn it off.

We (Homey and myself) are in contact with Hunter Hydrawise to use another meganism and then I hope to get rid of this update frequency (but get them from Hydrawise automatically).
