### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by rentisob** [mjilesen/com.hydrawise#9]
Dear Monique,

First of all, thank you for the app that you have created for Homey. 
I'm facing with an issue, when I'm starting a zone, it works absolutely fine, but when I want to stop it, then I'm getting back "Error: Request failed with status code 429".
Do you have any idea what can cause this issue?

I have created a diagnostics report: 8e4a9ea0-1ba4-4d04-8d68-a0a084c7fe45.

Thanks a lot,
Csaba

**Comment by mjilesen** [comment]
Hello,

 

Yes, Hydrawise has limited the amount of calls to their API that can happen and when you exceed that, you get this message.

 

Hydrawise:

*       The limit is 3 calls to start/stop/suspend a zone per 30 seconds.

*       There is an additional limit across the entire API of 30 calls in a 5 minute period per use

 

When a zone is running, the Homey app does also calls by itself to get the status of a zone. You can set this frequency in Homey->Apps->Hunter Hydrawise ->Configure App. 

I hope this information helps you to solve this issue.

 

Regards,

Monique

 

From: rentisob ***@***.***> 
Sent: Saturday, April 15, 2023 7:33 PM
To: mjilesen/com.hydrawise ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mjilesen/com.hydrawise] Error: Request failed with status code 429 (Issue #9)

 

Dear Monique,

First of all, thank you for the app that you have created for Homey.
I'm facing with an issue, when I'm starting a zone, it works absolutely fine, but when I want to stop it, then I'm getting back "Error: Request failed with status code 429".
Do you have any idea what can cause this issue?

Thanks a lot,
Csaba

**Comment by rentisob** [comment]
Dear Monique, 

Thank you for the fast response! 
I was not aware that Homey app also calls the status of the zones, that caused the issue. I have just adjusted the frequency and it seems that it's working now. 
Thanks a lot! 
Best regards, 
Csaba 

Feladó: "mjilesen" ***@***.***> 
Címzett: "mjilesen/com.hydrawise" ***@***.***> 
Másolatot kap: "rentisob" ***@***.***>, "Author" ***@***.***> 
Elküldött üzenetek: Vasárnap, 2023. április 16. 10:38:58 
Tárgy: Re: [mjilesen/com.hydrawise] Error: Request failed with status code 429 (Issue #9) 

Hello, 



Yes, Hydrawise has limited the amount of calls to their API that can happen and when you exceed that, you get this message. 



Hydrawise: 

* The limit is 3 calls to start/stop/suspend a zone per 30 seconds. 

* There is an additional limit across the entire API of 30 calls in a 5 minute period per use 



When a zone is running, the Homey app does also calls by itself to get the status of a zone. You can set this frequency in Homey->Apps->Hunter Hydrawise ->Configure App. 

I hope this information helps you to solve this issue. 



Regards, 

Monique 



From: rentisob ***@***.***> 
Sent: Saturday, April 15, 2023 7:33 PM 
To: mjilesen/com.hydrawise ***@***.***> 
Cc: Subscribed ***@***.***> 
Subject: [mjilesen/com.hydrawise] Error: Request failed with status code 429 (Issue #9) 



Dear Monique, 

First of all, thank you for the app that you have created for Homey. 
I'm facing with an issue, when I'm starting a zone, it works absolutely fine, but when I want to stop it, then I'm getting back "Error: Request failed with status code 429". 
Do you have any idea what can cause this issue? 

Thanks a lot, 
Csaba
